### ISSUE TITLE
S3 as main storage for images and video 

### ISSUE THREAD

**Issue by bopoda** [pawel-brzezinski/sulu-storage-bundle#8]
config.yml:
```
oneup_flysystem:
    adapters:
        storage_awss3v3:
            awss3v3:
                client: storage.s3_client
                bucket: '%s3.bucket_media%'
                prefix: media
                options:
                    ACL: 'public-read'

    filesystems:
        storage_awss3v3:
            adapter: storage_awss3v3
            alias: pb_storage_awss3v3
            plugins: [ 'pb_sulu_storage.flysystem.awss3v3.content_path.plugin' ]
        media_storage:
            adapter: storage_awss3v3
            alias: custom_alias_to_media_storage
            plugins: ['pb_sulu_storage.flysystem.awss3v3.content_path.plugin']

pb_sulu_storage:
    provider: flysystem
    flysystem:
        filesystem:
            storage: pb_storage_awss3v3
            format_cache: pb_storage_awss3v3
```

services.yml:
```
    storage.s3_client:
        class: Aws\S3\S3Client
        arguments:
            - version: 'latest'
              region: 'ca-central-1'
              credentials:
                  key: '%s3.key%'
                  secret: '%s3.secret%'
              visibility: 'public'
```

I'm trying to move assets (image + video) from local storage to S3 storage.
Using such an config, I have assets uploaded to S3. 
Images are shown fine on frontend.  

To play video, I'm trying to call URL: `{{ sulu_get_media_url(media) }}` - it fails with error 500 as it's trying to look for asset in local storage, not S3, although `storage_awss3v3` is in config (please look at the screenshot with trace, the asset url is absolute, and it's public)

![image](https://user-images.githubusercontent.com/881283/135984741-1d37d5e3-7a7c-4118-867d-598471a2e391.png)

Also, image preview is not generated from video.

Could you please put words how "video" issue can be solved for sulu 1.6? Is it necessary to store files I in local folder as well or should I override `MediaStreamController`?
Is it possible to build yml-config to upload everything to S3 and cache to local storage after the first request?)
